columnSuffix: null
contentColumnType: string
fieldGroup: 227b7bbb-fdd1-4fad-b3b3-bc8dc6d411ca # svsw Section
handle: photoLeft
instructions: ''
name: 'Photo Left'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Upload Left image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:f93ad09d-00b5-43c5-b494-8c628ac9803b' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
